# Generated by Django 3.2.2 on 2021-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Marca')),
                ('fundacion', models.DateField(blank=True, verbose_name='Año de Fundación')),
                ('logo', models.ImageField(blank=True, upload_to='retrogames/logos', verbose_name='Logo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Desarrollador',
                'verbose_name_plural': 'Desarrolladores',
                'ordering': ['nombre'],
            },
        ),
    ]
