# Generated by Django 3.2.2 on 2021-05-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retrojuegos', '0004_alter_videojuego_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lanzamiento', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('logo', models.ImageField(upload_to='pruebas/logos', verbose_name='Logo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Emulador',
                'verbose_name_plural': 'Emuladores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lanzamiento', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('logo', models.ImageField(upload_to='pruebas/logos', verbose_name='Logo')),
                ('foto', models.ImageField(upload_to='pruebas/foto', verbose_name='Foto')),
                ('especificaciones', models.TextField(verbose_name='Especificaciones técnicas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferente', models.BooleanField(verbose_name='Preferente')),
                ('observaciones', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Editado el')),
                ('emulador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.emulador', verbose_name='Emulador')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.maquina', verbose_name='Máquina')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrojuegos.videojuego', verbose_name='Juego')),
            ],
            options={
                'verbose_name': 'Prueba de rendimiento',
                'verbose_name_plural': 'Pruebas de rendimiento',
                'ordering': ['titulo'],
            },
        ),
    ]
