# Generated by Django 3.2.2 on 2021-05-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Marca')),
                ('fundacion', models.DateField(blank=True, verbose_name='Año de Fundación')),
                ('logo', models.ImageField(blank=True, upload_to='retrogames/logos', verbose_name='Logo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='logo',
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Modelo placa')),
                ('lanzamiento', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('foto', models.ImageField(upload_to='pruebas/foto', verbose_name='Foto')),
                ('especificaciones', models.TextField(verbose_name='Especificaciones técnicas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Editado el')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.marca', verbose_name='Marca fabricante')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['nombre'],
            },
        ),
    ]
