# Generated by Django 3.2.2 on 2021-05-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_maquina_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.marca', verbose_name='Fabricante'),
        ),
    ]
