# Generated by Django 3.2.2 on 2021-05-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0004_alter_maquina_fabricante'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='placa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.placa', verbose_name='Placa SBC'),
            preserve_default=False,
        ),
    ]
