# Generated by Django 3.2.2 on 2021-05-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0005_prueba_placa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placa',
            options={'ordering': ['nombre'], 'verbose_name': 'Placa', 'verbose_name_plural': 'Placas'},
        ),
    ]
