# Generated by Django 3.2.3 on 2021-05-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0006_alter_placa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Sistema')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Versión')),
                ('logo', models.ImageField(blank=True, upload_to='pruebas/so', verbose_name='Logotipo')),
                ('descarga', models.URLField(blank=True, verbose_name='Link de descarga')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Sistema Operativo',
                'verbose_name_plural': 'Sistemas operativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='prueba',
            name='so',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.so', verbose_name='Sistema operativo'),
            preserve_default=False,
        ),
    ]
