# Generated by Django 3.2.3 on 2021-05-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0007_auto_20210514_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='so',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebas.so', verbose_name='Sistema operativo'),
        ),
    ]
