# Generated by Django 3.2.3 on 2021-05-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0008_alter_prueba_so'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='favorito',
            field=models.BooleanField(default=1, verbose_name='Juego favorito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prueba',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='preferente',
            field=models.BooleanField(verbose_name='Mejor Emulador'),
        ),
    ]
