# Generated by Django 3.2.3 on 2021-05-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0009_auto_20210515_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='favorito',
        ),
    ]
