# Generated by Django 3.2.2 on 2021-05-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Marca')),
                ('fundacion', models.DateField(blank=True, verbose_name='Año de Fundación')),
                ('logo', models.ImageField(blank=True, upload_to='retrogames/logos', verbose_name='Logo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Sistema')),
                ('fecha_lanzamiento', models.DateField(blank=True, verbose_name='Fecha de lanzamiento')),
                ('generacion', models.CharField(choices=[('1', '1ª Generación'), ('2', '2ª Generación'), ('3', '3ª Generación'), ('4', '4ª Generación'), ('5', '5ª Generación'), ('6', '6ª Generación'), ('7', '7ª Generación'), ('8', '8ª Generación')], max_length=200, verbose_name='Generación')),
                ('logo', models.ImageField(blank=True, upload_to='retrogames/logos', verbose_name='Logo')),
                ('consola', models.ImageField(blank=True, upload_to='retrogames/consolas', verbose_name='Consola')),
                ('icono', models.ImageField(blank=True, upload_to='retrogames/iconos', verbose_name='Icono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Editado el')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrojuegos.fabricante', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ['nombre'],
            },
        ),
    ]
