# Generated by Django 3.2.2 on 2021-05-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_desarrollador'),
        ('retrojuegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegoretro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Título')),
                ('lanzamiento', models.DateField(blank=True, verbose_name='Fecha de lanzamiento')),
                ('jugadores', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20, null=True, verbose_name='Nº de Jugadores')),
                ('valoracion', models.FloatField(blank=True, verbose_name='Valoración')),
                ('caja', models.ImageField(blank=True, upload_to='retrogames/portadas', verbose_name='Portada')),
                ('video', models.FileField(blank=True, upload_to='retrogames/videosnaps', verbose_name='Video preview')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('desarrollador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.desarrollador', verbose_name='Desarrollador')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.genero', verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Videojuego retro',
                'verbose_name_plural': 'Videojuegos retro',
                'ordering': ['nombre'],
            },
        ),
    ]
