# Generated by Django 3.2.3 on 2021-05-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrojuegos', '0004_alter_videojuego_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='descarga',
            field=models.URLField(default=1, verbose_name='Link de descarga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='logo',
            field=models.ImageField(blank=True, upload_to='pruebas/logos', verbose_name='Logo'),
        ),
    ]
