# Generated by Django 3.2.3 on 2021-05-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrojuegos', '0005_auto_20210514_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='descarga',
            field=models.URLField(blank=True, verbose_name='Link de descarga'),
        ),
    ]
