# Generated by Django 3.2.3 on 2021-05-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrojuegos', '0006_alter_sistema_descarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='lanzamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento'),
        ),
    ]
