# Generated by Django 3.2.3 on 2021-05-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrojuegos', '0008_auto_20210515_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='favorito',
            field=models.BooleanField(default=0, verbose_name='Juego favorito'),
            preserve_default=False,
        ),
    ]
