# Generated by Django 3.2.3 on 2021-05-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retrojuegos', '0009_videojuego_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='sistema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='retrojuegos.sistema', verbose_name='Sistema'),
            preserve_default=False,
        ),
    ]
