# Generated by Django 3.2.3 on 2021-05-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrojuegos', '0010_videojuego_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='retrogames/banners', verbose_name='Banner'),
        ),
    ]
